# Generated by Django 3.0.2 on 2020-10-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='atualizado_em',
            field=models.TextField(blank=True),
        ),
    ]
