# Generated by Django 3.0.2 on 2020-10-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pais', '0002_pais_atualizado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='imagem',
            field=models.ImageField(default='', upload_to='images/pais/'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='atualizado_em',
            field=models.DateField(default=''),
        ),
    ]
