# Generated by Django 3.0.2 on 2020-10-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pais', '0003_auto_20201002_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='religiao',
            name='descricao',
            field=models.TextField(blank=True),
        ),
    ]
