# Generated by Django 3.0.2 on 2020-10-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pais', '0005_auto_20201002_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moeda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(blank=True)),
                ('imagem', models.ImageField(default='', upload_to='images/moedas/')),
            ],
            options={
                'db_table': 'moeda',
            },
        ),
    ]
