# Generated by Django 3.0.2 on 2020-10-02 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pais', '0006_moeda'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='moeda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='pais.Moeda'),
        ),
    ]
