# Generated by Django 3.0.2 on 2020-10-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pais', '0007_pais_moeda'),
    ]

    operations = [
        migrations.AddField(
            model_name='turismo',
            name='nome',
            field=models.TextField(blank=True),
        ),
    ]
