# Generated by Django 3.0.2 on 2020-10-02 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pais', '0008_turismo_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turismo',
            old_name='decricao',
            new_name='descricao',
        ),
    ]
