# Generated by Django 3.0.2 on 2020-10-24 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'avatar',
            },
        ),
        migrations.CreateModel(
            name='PalavraVida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('motivacao', models.TextField()),
                ('localidade', models.CharField(default='', max_length=250)),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='palavra_vida.Avatar')),
            ],
            options={
                'db_table': 'palavra_vida',
            },
        ),
    ]
