# Generated by Django 3.0.2 on 2020-10-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conquista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(db_index=True, max_length=100, unique=True)),
                ('descricao', models.TextField(default='')),
                ('documento', models.FileField(blank=True, upload_to='documentos/conquistas/')),
                ('localidade', models.CharField(default='', max_length=250)),
                ('link', models.CharField(blank=True, max_length=150)),
                ('data', models.DateField(default='')),
            ],
            options={
                'db_table': 'conquista',
                'ordering': ('data',),
            },
        ),
    ]
